# This workflow has been archived during the project transition.
# It was previously used for running security audits using Inrupt's infrastructure.
# A new security audit workflow should be implemented by the new maintainers.
#
# Original workflow file below:
# ----------------------------------------

name: Audit

on:
  push:
  schedule:
    - cron: "40 10 * * *"

jobs:
  audit:
    uses: inrupt/typescript-sdk-tools/.github/workflows/reusable-audit.yml@v2.0.4
    secrets:
      WEBHOOK_E2E_FAILURE: ${{ secrets.WEBHOOK_E2E_FAILURE }}
