name: CI

on: [push]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
          # is not included the project will show a warning about incomplete information.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
